### ISSUE TITLE
my makefile, erros

### ISSUE THREAD

**Issue by hiostreas** [Algomorph/pyboostcvconverter#1]

**Comment by hiostreas** [comment]
makefile 

PYTHON_VERSION = 2.7
PYTHON_INCLUDE = /usr/include/python$(PYTHON_VERSION)

BOOST_INC = /usr/local/include
BOOST_LIB = /usr/local/lib
OPENCV_LIB = $$(pkg-config --libs opencv)
OPENCV_INC = $$(pkg-config --cflags opencv)

TARGET = matmul

$(TARGET).so: $(TARGET).o
    g++ -shared -Wl,--export-dynamic $(TARGET).o -L$(BOOST_LIB) -lboost_python -lboost_numpy $(OPENCV_LIB) -L/usr/lib/python$(PYTHON_VERSION)/config -lpython$(PYTHON_VERSION) -o $(TARGET).so

$(TARGET).o: $(TARGET).cpp
    g++ -I$(PYTHON_INCLUDE) $(OPENCV_INC) -I$(BOOST_INC) -fPIC -c $(TARGET).cpp

ERRORS

matmul.cpp: In function ‘PyObject\* mul(PyObject_, PyObject_)’:
matmul.cpp:12:10: error: ‘c1’ does not name a type
     auto c1 = leftMat.cols, r2 = rightMat.rows;
          ^
matmul.cpp:14:9: error: ‘c1’ was not declared in this scope
     if (c1 != r2)
         ^
matmul.cpp:14:15: error: ‘r2’ was not declared in this scope
     if (c1 != r2)
               ^
matmul.cpp: In function ‘cv::Mat mul2(cv::Mat, cv::Mat)’:
matmul.cpp:31:10: error: ‘c1’ does not name a type
     auto c1 = leftMat.cols, r2 = rightMat.rows;
          ^
matmul.cpp:32:9: error: ‘c1’ was not declared in this scope
     if (c1 != r2)
         ^
matmul.cpp:32:15: error: ‘r2’ was not declared in this scope
     if (c1 != r2)
               ^
matmul.cpp: In function ‘void init_module_matmul()’:
matmul.cpp:51:23: error: ‘XM’ is not a namespace-name
       using namespace XM;
                       ^
matmul.cpp:51:25: error: expected namespace-name before ‘;’ token
       using namespace XM;
                         ^
make: **\* [matmul.o] Error 1

**Comment by Algomorph** [comment]
I think in order for auto vars to work, you need to use C++11. Try building with the -std=c++11 flag for g++.

**Comment by hiostreas** [comment]
I could use that command But I still having the same issue

**Comment by Algomorph** [comment]
What's your GCC version?

**Comment by hiostreas** [comment]
I had to switch The pointer of the compiler iam using 4.8

**Comment by Algomorph** [comment]
What happens when you replace `auto` with `int`? (in all places of the sample code)

**Comment by Algomorph** [comment]
Am I save to assume that solved the issue? Can I now close it?

**Comment by hiostreas** [comment]
That didnt help

**Comment by Algomorph** [comment]
Building with the `-std=c++0x` flag seems to take care of this error for me.

**Comment by ortizeg** [comment]
I am having the same issue and receive the error upon using namespace XM. I have tried using the flags '-std=c++11 -stdlib=libc++' to enable C++11. When I run the command 'g++ --version', I receive the following output:

g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

Any suggestions?

**Comment by Algomorph** [comment]
Hello, gentlemen, I just got back from my vacation. I have an updated version, which should work for OpenCV 2.10+ and OpenCV 3.0 interchangeably. I still need to perform testing with the OpenCV 3.0 + version and incorporate the changes into the repo. The new version uses CMake. Hopefully, that should take of the issue.

@ortizeg , I have been using gcc 4.7 through 4.9 for this. Could outdated gcc includes (4.2) be the issue?

**Comment by ortizeg** [comment]
I tried gcc 4.9 and it produced a similar error: "matmul.cpp:51:21: error: 'XM' is not a namespace-name".

**Comment by Algomorph** [comment]
Hi @ortizeg, 
could you please try out the newer version in the feature/cmake branch?

P.S. you'll need to use cmake to generate the Makefiles. This should simplify things a bit. On *nix systems, something like "sudo make install" will also install the compiled library to the needed folder.

**Comment by Algomorph** [comment]
Fixed in a304f8c94a37d4533bf660bf7fe2a0e4fec7a581
