### ISSUE TITLE
Issue in Building libraries from cpp code generated using CMake in windows 

### ISSUE THREAD

**Issue by swatinair123** [Algomorph/pyboostcvconverter#14]
Hi i have generated the C++ code using CMake and then i am trying to build the libraries . I have selected ALL_BUILD for building it. But it gives me error while building the code .It says its not able to find ..../../..zlib.lib.Can you please help

**Comment by Algomorph** [comment]
Do you have [zlib.lib](https://zlib.net/) on your machine? Have you tried setting the path to it via CMake-GUI?
I'm not sure why it's checking for it on your machine: the requirements in the CMake are OpenCV, python, numpy, and Boost. Perhaps it's a requirement of OpenCV?

**Comment by swatinair123** [comment]
Hi i was able to resolve the issue. I have succesfully configured and generated the cpp projects(ALL_BUILD,INSTALL,ZERO_CHECK and pbcvt) . But when i build it it gives me Linker error saying cant open file LNK1104	cannot open file 'boost_pythonPY_MAJOR_VERSIONPY_MINOR_VERSION-vc141-mt-x64-1_67.lib'.

Is this an issue regarding the boost library i have downloaded. I have downloaded boost_1_66_0.7z from https://www.boost.org/users/history/version_1_64_0.html . Or should i download from else where. Can you please help me resolve it.
I have also tried resolving as per suggestion in  https://github.com/boostorg/python/issues/193 .But no luck.

Can you also tell me what should be set to 
boost_PYTHON-PY36_LIBRARY_DEBUG and boost_PYTHON-PY36_LIBRARY_RELEASE in CMAKE under BOOST for configuration

**Comment by Algomorph** [comment]
Hi, @swatinair123 , I'm sorry you're having trouble. Have you compiled boost? Do you have the actual boost libraries and .lib files? Did you compile in dynamic form or static?

A more strategic question: are you limited to using Windows? All of this should be possible in Windows, but you might have to compile a lot of stuff and manually set the CMake GUI options, so it takes a bit of experience and patience with the "Microsoft way of doing things". If you're new to CMake, I think it would be much easier to start on Linux.

**Comment by swatinair123** [comment]
Hi I am now able to build the project in Visual studio without any issue.I have converted pbcvt to .lib instead of .exe . Can you please let me know incase I have to write a Main function which wich converts ndarraytoMat how should i go about it. Can I add main to python_module.cpp. Acuallt i have a c code whcih has APi which returns a ndArray. So how can i use it. In case i create a .lib for pbcv what is the header files to be added in the Main cpp.

**Comment by Algomorph** [comment]
@swatinair123 , this project is intended to be built as a dynamic library which is then used inside python. I don't know how you got your executable in the first place, since clearly, the CMake command is "add_library", not "add_executable". I don't understand why would you ever want a C++ executable using this code, since this whole sample project is aimed at showing people how they can use their C++ code that uses OpenCV from within python with ease. I don't understand your question or what you're trying to do.

**Comment by swatinair123** [comment]
OK.yes I did not build a. Exe file. I had built a. Lib. Ok now I will convert it into. Dll. Actually tried using the. Lib in my project. But that was giving me errors. So tats why I was trying to add main to pbcv project. Now I will create a. Dll and use it in my project

**Comment by Algomorph** [comment]
As a response to earlier problem,  

> Linker error saying cant open file LNK1104	cannot open file 'boost_pythonPY_MAJOR_VERSIONPY_MINOR_VERSION-vc141-mt-x64-1_67.lib'.

This is a boost error, which should be fixed soon, [see this thread](https://github.com/boostorg/python/issues/193).
Adding the  /DBOOST_ALL_NO_LIB compile flag to CMAKE_CXX_FLAGS in CMake-GUI seems to have fixed it for me.

**Comment by Algomorph** [comment]
Ok, from the sound of it, it's looking like you are using python 3. The dynamic library file will be a .pyd, and building the install target should put it into the correct folder for later import in python. If you have further problems,

1) Verify that you have the dynamic library, the .pyd file, in the Lib\site-packages directory within your python distro.
2) Use [dependency walker ](http://www.dependencywalker.com/) to make sure it can find all of the 1-st level dynamic library requirements for the .pyd file. For instance, one Windows pitfall I just forgot about myself was that opencv libraries have to be in the system path. Also make sure that architecture of your build matches your python, and that msvc version matches on all of the binaries you're using (boost libraries, OpenCV libraries, pbcvt.[version-string].pyd).
