### ISSUE TITLE
ImportError: No module named pbcvt 

### ISSUE THREAD

**Issue by swatinair123** [Algomorph/pyboostcvconverter#15]
How can i install pbcvt for python to be used in Python code in windows Anacoda prompt. I have already build the c++ code using CMake and build the libraries using Visual studio. when i import pbcvt itt says module error .No module named pbcvt. c

**Comment by Algomorph** [comment]
Did you build the install CMake target? Did you check that you have the pbcvt library inside the python system path? (Shouldn't that be a dynamic, not static library, by the way? I don't clearly remember how things with Python work on Windows, but dynamic library -- .dll, not .lib, seems like the only option).

**Comment by Algomorph** [comment]
On an unrelated note, please use proper punctuation in your posts, e.g. "?" instead of "." at the end of questions, etc. This will make them easier to read not only for me, but for generations to come! :)

**Comment by Algomorph** [comment]
I've dusted off a Windows box and replicated this issue: I am getting the generated .pyd file (which is a dynamic library) in the site-packages directory for the python distribution, but I'm too getting an import error. I'll be trying to resolve this further, but it will take more time. This may stem from a change in semantics of how library imports are performed in python.

**Comment by Algomorph** [comment]
Ok, my import error was not really an error, I forgot to add opencv dynamic libraries to the system PATH, after this my import was fine.

**Comment by Algomorph** [comment]
@swatinair123 , I haven't heard from you in awhile. I'll wait a little longer, and then assume that you resolved the issues on your platform and close the issues here.
