### ISSUE TITLE
Mistmatch in function signature.

### ISSUE THREAD

**Issue by kanaero** [Algomorph/pyboostcvconverter#2]
In pyboostcvconverter.hpp 
Mat fromNDArrayToMat(const PyObject\* o); 
In pyboost_cv3_converter.cpp
Mat fromNDArrayToMat(PyObject\* o){..}

resulting in a undefined symbol when import pycvt is called when using the CV3 converters. Fix is probably to add a const qualifer in pyboost_cv3_converter.cpp for the function
Mat fromNDArrayToMat(const PyObject\* o){..}
and cast away the const in line 265
m.u = g_numpyAllocator.allocate((PyObject*)o, ndims, size, type, step);

**Comment by Algomorph** [comment]
Fixed in 503e3aee804105d2c94736cd5f62134aa84ac86a
