### ISSUE TITLE
segfault with OpenCV3 converter

### ISSUE THREAD

**Issue by kanaero** [Algomorph/pyboostcvconverter#3]
The converters for OpenCV3 do not seem to work. When trying the following standalone code, things work until pbcvt.dot2(a,b) is called. When debugging everything is ok until the return statement at the bottom of the dot2 function.

import pbcvt; import numpy as np
a = np.array([[1.,2.],[3.,4.]]); b = np.array([[2.,2.],[4.,4.]])
pbcvt.dot(a,b)
pbcvt.dot2(a,b)

**Comment by Algomorph** [comment]
Thanks for reporting this, I'll take a look at it again. I have to go through certain motions for this, i.e.  switch from OpenCV 2.4.11 to OpenCV3, so there might be a delay.

**Comment by Algomorph** [comment]
Should be fixed with latest commit (7f25794f6a42d7231e2ac589733c79c17d6a71c9). Please check on your end and reopen the issue if need be.

**Comment by kanaero** [comment]
Everything works including OpenCV3 converters.
Thanks
Suresh.
