### ISSUE TITLE
a typo resulting in inability generating the .so file for python2

### ISSUE THREAD

**Issue by feiyang-cai** [Algomorph/pyboostcvconverter#35]
In your [CMakeLists.txt, line 114:](https://github.com/Algomorph/pyboostcvconverter/blob/master/CMakeLists.txt#L114).
It should be ${PYTHON_DESIRED_VERSION}, there is a $ missing. This results that it cannot generate a .so file for python2.

**Comment by Algomorph** [comment]
@feiyangsb thanks, fixed!
