### ISSUE TITLE
cannot open file 'python27.lib'

### ISSUE THREAD

**Issue by aligoglos** [Algomorph/pyboostcvconverter#40]
I've tried to build project on windows that error occurred. I don't Have python27 and don't want to have!
I set PYTHON_DESIRED_VERSION to 3.X but still project depend on python27 why??

**Comment by Algomorph** [comment]
You need to regenerate the project completely via CMake first, and then reopen the solution in VS. Have you tried this?

**Comment by aligoglos** [comment]
yes i tried that but still solution had problem!
isn't any preprocess definition, can i add manually?

**Comment by Algomorph** [comment]
@aligoglos I am unable to replicate your issue using VS 2017 / Python 3.7 / CMake 3.15.2 / OpenCV 4.1 / Boost 1.70 on a Windows 10 VM without any Python 2.7 installation. Try again from a clean slate, perhaps?

**Comment by aligoglos** [comment]
I completely cleaned and regenerated solution again with cmake but still I've had that issue.
I've used VS2015 / Python 3.5.4 / CMake 3.14.1 / OpenCV 3.4.6 / Boost 1.64.0 on windows 10.

**Comment by aligoglos** [comment]
I upgrade boost to 1.7 and CMake 3.15.2 the problem resolved.
