### ISSUE TITLE
CMake 

### ISSUE THREAD

**Issue by crocis** [Algomorph/pyboostcvconverter#43]
I have a problem when building the code with CMake. OpenCV is not found when running "cmake ../". I have installed opencv in Ubuntu with the command "apt install python3-opencv".

**Comment by crocis** [comment]
Problem solved. I have compiled OpenCV from the source code and I have called cmake specifying OpenCV_DIR equal to the location where OpenCV was installed.

**Comment by Algomorph** [comment]
Right, this has been the only viable alternative. Unfortunately, `apt install python3-opencv` does not have the development files (e.g. headers) that are required, while the  `libopencv-dev` apt package does not come with the OpenCV python3 module prebuilt (which is desirable to most folks nowadays).
