### ISSUE TITLE
Unresolved external symbol pbcvt_ARRAY_API 

### ISSUE THREAD

**Issue by b-sia** [Algomorph/pyboostcvconverter#48]
I tried to build the project but I got an unresolved external symbol error. The pvcvt_ARRAY_API could not be found by NumpyAllocator::Allocate().

![Screenshot from 2022-01-30 16-04-30](https://user-images.githubusercontent.com/9401015/151737015-b6b36cf0-60bb-47a4-b08e-48ad155e8d0a.png)

pbcvt_ARRAY_API points to the PyArray_API in  NumPy's __multiarray_api.h. Based on my knowledge, PyArray_API is declared and consumed by NumpyAllocator::Allocate(), but the definition (.dll or lib?) could not be found at link time. 

Does the PyArray_API have a dll that is required during link time?

**Comment by Algomorph** [comment]
So far, I haven't been able to replicate.
1. When you say, "build the project", do you mean the test project or just the PBCVT static library? Or, perhaps, your own project based on the test project? (there's an option in CMake that enables the test project build).
2. What OS are you running the build on?
3. If it's MacOS or Linux and you have the right `pip` (or equivalent, e.g. conda), can you give me the outputs of the following commands from your build folder:
`pip show numpy` (or just tell me the NumPy version for the python deployment that you're linking against)
`cat CMakeCache.txt | grep PYTHON_DESIRED_VERSION`
`cat CMakeCache.txt | grep NUMPY_INCLUDE_DIRS`

**Comment by b-sia** [comment]
Hi Algo,

It seems like I found a fix for my problem. I changed the output type from .exe to .dll and disabled the **#define NO_IMPORT_ARRAY** and **#define PY_ARRAY_UNIQUE_SYMBOL pbcvt_ARRAY_API** directives. 

https://numpy.org/doc/1.17/reference/c-api.array.html should give us an idea as to how this works, under _Importing the API_. I do not know the exact details but it seems that it has something to do with the the API's visibility to other compilation units.

EDIT: I take back what I said. Although the compilation is success after removing the directives, I got an access violation when trying to call a function with the API. Specifically, _PyArray_Check_ inside _fromNDArrayToMat_.

**Comment by Algomorph** [comment]
@zerovirus123 , please answer the questions I posted earlier. I am unable to replicate your problem with my own setup, and I don't know what your setup is. If I can't replicate the problem, it is highly unlikely that I will able to help out.

**Comment by Algomorph** [comment]
Closing due to lack communication.
