### ISSUE TITLE
Has anyone tried compiling via vs on a windows system?

### ISSUE THREAD

**Issue by rememberBr** [Algomorph/pyboostcvconverter#49]
as the title

**Comment by Algomorph** [comment]
I'm guessing you've seen the VS 2017 and VS 2019 compilations / logs in the CI AppVeyor tests (test badge on README). Feel free to ask any questions in a separate issue.

**Comment by rememberBr** [comment]
First of all thank you for replying to me in your busy schedule.
Sorry, I missed the closed issus and readme before, it was my fault, now I have completed the compilation through vs2015, by compiling boost_python and opencv according to the python version, setting the include directory in vs2015, linking the library directory, compiling as . pyd file, and successfully completed the test, just need to copy the .pyd file, the static link library of boost_python, and the dynamic library of opencv to the DLLs directory in the python directory.
environment :
1. window10x64
2. vs2015
3. opencv 3.4
4. boost 1.66
thanks again for your work
