### ISSUE TITLE
where is the 'pbcvt_ARRAY_API' define?

### ISSUE THREAD

**Issue by hengyanchen** [Algomorph/pyboostcvconverter#50]
i'm sorry! this is not a bug post, i use part of your code, but i can‘t find  'pbcvt_ARRAY_API' define，help me please! thanks!

**Comment by Algomorph** [comment]
It's just a name for the extension's array api. Please consult[ this link](https://numpy.org/devdocs/reference/c-api/array.html#c.NO_IMPORT_ARRAY) for reference. There is no definition, it's just a preprocessor literal. I hope this helps.

**Comment by Algomorph** [comment]
I'm guessing the issue is resolved, if not please feel free to reopen.

**Comment by hengyanchen** [comment]
yes, thanks for your help!
