### ISSUE TITLE
converting vector<Mat> to tuple(numpy array) in python

### ISSUE THREAD

**Issue by rajatsaxena** [Algomorph/pyboostcvconverter#9]
I am trying to convert vector of Mat to tuple of numpy array. Here is the detail of the problem I am facing: http://stackoverflow.com/questions/42919209/convert-vector-of-mat-cpp-to-python-list-of-numpy-array

Can you please take a look at the conversion scripts and suggest how to extend it? 

Thanks!

**Comment by Algomorph** [comment]
What type is "InputImage"?

**Comment by rajatsaxena** [comment]
I am trying to pass a tuple of numpy array(opencv images) from Python to C++ function where it should get converted to vector <Mat> and then return ithe vector back to Python as tuple og numpy array .

So basically InputImage is tuple of numpy arrays (tuple of multiple images read using opencv)

**Comment by Algomorph** [comment]
Well, as the compiler is saying, I don't think there's anything to handle a conversion of ‘std::vector<cv::Mat>’ to ‘PyObject*’ automatically, so you gotta handle that somewhere. Only conversion of 'cv::Mat' itself to 'PyObject*' is handled by my converter. I suggest you handle that manually, i.e. write another function for it.

**Comment by Algomorph** [comment]
@rajatsaxena , actually, why are you passing in a tuple? Is it a fixed-size tuple? Why not just make a practical solution and pass the matrices as separate arguments?

**Comment by rajatsaxena** [comment]
@Algomorph  No, it is not a fixed size tuple. My requirement is to pass tuple of varying size. That is why so much of hassle. Otherwise, I would have opted for the solution proposed by you. In https://github.com/opencv/opencv/blob/92c4b6ae4cc14bc32355f91fb755e84a9a834db4/modules/python/src2/cv2.cpp#L1228, OpenCV library does convert tuple(numpy array) to vector(Mat) but I am not able to integrate it.

**Comment by rajatsaxena** [comment]
@Algomorph  also I have written the converter here: https://github.com/rajatsaxena/pyImageListToVectorMatcpp/blob/master/src/pyboost_cv2_converter.cpp as  function _fromTupleToVector_ and _fromVectorToTuple_

**Comment by Algomorph** [comment]
@rajatsaxena well, hold on, I'm kind-of confused. Your 'InputImage' is already a vector of cv::Mat, not a tuple of numpy arrays, like you said. What step is your thing breaking down on, converting the arguments from python to cv::Mat (in which case that would be solved, i.e. you wouldn't need to call anything if you already got a vector of cv::Mat)? Or is the problem in the outputting of the result as a tuple of ndarrays (in which case you need to call fromVectorToTuple instead)?

**Comment by rajatsaxena** [comment]
Ohh Sorry for the confusion. Here are the steps used in my algorithm:

1. take tuple of NDArray as input from python to C++ function
2. convert tuple of NDArray to vector of Mat 
3. perform some processing on vector of mat and generate new vector of mat
4. convert that vector of mat to tuple of NDArray
4. return the tuple of NDArray back to python

Now my problem is on Step 2 i.e. tuple of NDArray to vector of Mat conversion (_fromTupleToVector')

Thanks for all the help till now

**Comment by Algomorph** [comment]
@rajatsaxena , have you solved this? I'm sorry about not following up earlier, you only got back to me after two days and the notification got lost among other ones in my mail. Multiple software projects, extreme multithreading :-)

If not, look closely at this line within your code:
```C++
vector<Mat> InputImage = pbcvt::fromTupleToVector(InputImage);
```
Should the second InputImage be capitalized? ;-)

**Comment by rajatsaxena** [comment]
Thanks that resolved the error. The code generates .so file but when I try to import it I get an undefined reference error, so sorting that out now.
